favicon: null
name: Little Piata
opengraph:
  image: null
  type: null
  appId: null
collections:
  - index:
      path: /
      number: 15
      paginate: true
      navigable: true
    permalink:
      path: '/:title/'
    feed:
      path: /rss.xml
      format: rss
      number: 10
purpose: []
color:
  saturation: 0.7902335550170392
  brandStrength: 1
  lightness: 0.142820700770244
  brandColors:
    - '#F8EFE1'
    - '#281E16'
    - '#88421F'
    - '#CFB3A4'
    - '#B3CEE9'
  rhythmicContrast: 0.7694862550124526
typography_spectrum: 0.6306493147276342
layout_spectrum: 0.7404698843602091
analytics:
  twitter: null
  google: null
  facebook: null
cta:
  bucket: null
  version: null
  domain: null
