name: Little Piata
favicon: null
layout_spectrum: 0.7404698843602091
typography_spectrum: 0.6306493147276342
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#A690A4'
    - '#B68F9D'
    - '#C8ACAB'
    - '#FBB9BF'
    - '#E376B7'
  brandStrength: 0.9962789376731962
  lightness: 0.142820700770244
  saturation: 0.7902335550170392
  rhythmicContrast: 0.7694862550124526
purpose: []
